apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: bitcoind
  name: bitcoind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitcoind
  template:
    metadata:
      labels:
        app: bitcoind
      name: bitcoind
    spec:
      containers:
      - args:
        env:
        - name: JAVA_OPTS
          value: -Xms256m -Xmx3072m
        image: nicolasdorier/docker-bitcoin:0.18.1
        imagePullPolicy: Always
        name: bitcoind
#        livenessProbe:
#          failureThreshold: 3
#          httpGet:
#            path: /v1/ping
#            port: 8080
#            scheme: HTTP
#          initialDelaySeconds: 30
#          periodSeconds: 10
#          successThreshold: 1
#          timeoutSeconds: 10
#        readinessProbe:
#          failureThreshold: 30
#          httpGet:
#            path: /v1/ping
#            port: 8080
#            scheme: HTTP
#          initialDelaySeconds: 30
#          periodSeconds: 1
#          successThreshold: 1
#          timeoutSeconds: 10
#        resources:
#          limits:
#            cpu: "1"
#            memory: 3G
#          requests:
#            memory: 1500M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: bitcoin-blockchain-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 0
      terminationGracePeriodSeconds: 30
      volumes:
      - name: bitcoin-blockchain-data
        persistentVolumeClaim:
          claimName: bitcoin-blockchain-pvc-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  name: bitcoin-blockchain-pvc-claim
spec:
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 350Gi
  storageClassName: standard
  volumeMode: Filesystem