apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: btc-rpc-explorer
  name: btc-rpc-explorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: btc-rpc-explorer
  template:
    metadata:
      labels:
        app: btc-rpc-explorer
      name: btc-rpc-explorer
    spec:
      containers:
      - args:
        env:
        - name: BTCEXP_BITCOIND_HOST
          value: bitcoind
        - name: BTCEXP_BITCOIND_USER
          value: h0ngcha0
        - name: BTCEXP_BITCOIND_PASS
          value: h0ngcha0
        image: liuhongchao/btc-rpc-explorer:latest
        imagePullPolicy: Always
        name: btc-rpc-explorer
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 0
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: btc-rpc-explorer
spec:
  selector:
    app: btc-rpc-explorer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: ClusterIP
